steps:
  # ----------------------------------------------------------------------
  # Step 0: Validate required substitutions
  # ----------------------------------------------------------------------
  - name: 'bash'
    id: 'validate-substitutions'
    entrypoint: 'bash'
    args:
      - -c
      - |
        if [ -z "${_REGION}" ] || [ -z "${_PROJECT_ID}" ] || [ -z "${_ARTIFACT_REPO}" ] || \
           [ -z "${_GKE_CLUSTER}" ] || [ -z "${_GKE_LOCATION}" ] || [ -z "${_NS}" ] || \
           [ -z "${SHORT_SHA}" ] || [ -z "${BRANCH_NAME}" ]; then
          echo "Error: One or more required substitutions are missing."
          exit 1
        fi
        echo "All substitutions validated successfully."

  # ----------------------------------------------------------------------
  # Step 0.5: SSH setup for Git authentication
  # ----------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    id: 'ssh-setup'
    waitFor: ['validate-substitutions']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Setting up SSH for Git authentication..."
        mkdir -p /root/.ssh
        echo "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
        echo "SSH setup complete."
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # ----------------------------------------------------------------------
  # Step 1: Clone repository
  # ----------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone-repo'
    waitFor: ['ssh-setup']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Cloning repository..."
        git clone --recurse-submodules git@github.com:HYPR4/unicommerce.git
        cd unicommerce
        git checkout $BRANCH_NAME
        echo "Repository cloned and checked out to branch: $BRANCH_NAME"
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # ----------------------------------------------------------------------
  # Step 2: Detect changed services (only dirs with Dockerfile)
  # ----------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/git'
    id: 'detect-changes'
    waitFor: ['clone-repo']
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd unicommerce
        echo "Current directory: $(pwd)"
        echo "Branch: $BRANCH_NAME"

        git fetch origin $BRANCH_NAME --depth=2
        echo "Latest commit:"
        git log -1 --oneline

        # Get changed files (or all files on first commit)
        changed_files=$(git diff --name-only HEAD^ HEAD 2>/dev/null || git ls-tree -r HEAD --name-only)
        echo "All changed files:"
        echo "$changed_files"

        # Keep only backend/ and frontend/ paths
        changed_files=$(echo "$changed_files" | grep -E "^(backend|frontend)/" || true)
        echo "Relevant changed files:"
        echo "$changed_files"

        # Find all directories containing Dockerfile
        services=$(find backend frontend -type f -name Dockerfile -exec dirname {} \; | sort -u)
        if [ -z "$services" ]; then
          echo "Warning: No Dockerfiles found."
          echo "" > /workspace/changed_services.txt
          exit 0
        fi

        echo "All services with Dockerfile:"
        echo "$services"

        # Determine which services have changes
        changed_services=""
        for svc in $services; do
          if echo "$changed_files" | grep -q "^$svc/"; then
            changed_services="$changed_services $svc"
          fi
        done
        changed_services=$(echo "$changed_services" | xargs)

        echo "$changed_services" > /workspace/changed_services.txt
        echo "Changed services to build/deploy:"
        cat /workspace/changed_services.txt
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # ----------------------------------------------------------------------
  # Step 3: Skip if no changes
  # ----------------------------------------------------------------------
  - name: 'bash'
    id: 'check-if-changes-exist'
    waitFor: ['detect-changes']
    entrypoint: 'bash'
    args:
      - -c
      - |
        if [ ! -s /workspace/changed_services.txt ] || [ "$(cat /workspace/changed_services.txt | tr -d '[:space:]')" = "" ]; then
          echo "No changed services detected. Skipping remaining steps."
          echo "SKIP_BUILD=true" > /workspace/build_status.txt
          exit 0
        fi
        echo "SKIP_BUILD=false" > /workspace/build_status.txt
        echo "Changes detected. Proceeding with build and deployment."

  # ----------------------------------------------------------------------
  # Step 5: Build & Push Docker Images (Parallel + Cache)
  # ----------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-and-push'
    waitFor: ['check-if-changes-exist']
    entrypoint: 'bash'
    args:
      - -c
      - |
        if grep -q "SKIP_BUILD=true" /workspace/build_status.txt; then
          echo "Skipping Docker build."
          exit 0
        fi

        cd /workspace/unicommerce
        changed_services=$(cat /workspace/changed_services.txt)
        if [ -z "$changed_services" ]; then
          echo "No services to build."
          exit 0
        fi

        # Helper function
        build_and_push_service() {
          local service=$1
          local service_basename=$(basename "$service")
          # Normalize: lowercase + underscores → hyphens
          local service_name=$(echo "$service_basename" | tr '[:upper:]' '[:lower:]' | sed 's|_|-|g')

          local img_short="${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/$service_name:$SHORT_SHA"
          local img_latest="${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/$service_name:latest"

          echo "=========================================="
          echo "Building: $service_name"
          echo "  Dir : $service"
          echo "  Tag : $img_short"
          echo "  Cache: $img_latest"
          echo "=========================================="

          # Pull latest for cache
          docker pull "$img_latest" || echo "No cache image. Building from scratch."

          # Build with BuildKit + cache
          DOCKER_BUILDKIT=1 docker build \
            --cache-from "$img_latest" \
            --tag "$img_short" \
            --tag "$img_latest" \
            "$service"

          # Push in parallel
          docker push "$img_short" &
          local p1=$!
          docker push "$img_latest" &
          local p2=$!
          wait $p1 $p2

          echo "Successfully built & pushed: $service_name"
        }

        # Parallel builds
        pids=()
        for svc in $changed_services; do
          build_and_push_service "$svc" &
          pids+=($!)
        done

        echo "Waiting for all ${#pids[@]} builds to complete..."
        for pid in "${pids[@]}"; do
          if ! wait $pid; then
            echo "Build failed for PID $pid"
            exit 1
          fi
        done

        echo "All Docker images built and pushed!"

  # ----------------------------------------------------------------------
  # Step 6: Update Kubernetes Manifests
  # ----------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-manifests'
    waitFor: ['build-and-push']
    entrypoint: 'bash'
    args:
      - -c
      - |
        if grep -q "SKIP_BUILD=true" /workspace/build_status.txt; then
          echo "Skipping manifest update."
          exit 0
        fi

        cd /workspace/unicommerce/infra/kubernetes
        changed_services=$(cat /workspace/changed_services.txt)

        for svc in $changed_services; do
          svc_basename=$(basename "$svc")
          svc_name=$(echo "$svc_basename" | tr '[:upper:]' '[:lower:]' | sed 's|_|-|g')
          img="${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/$svc_name:$SHORT_SHA"

          if [ "$svc_name" = "export-data" ]; then
            echo "=== Updating export-data (Job Template + CronJobs) ==="
            # Update job-template.yaml and all cronjobs
            find . -type f \
              \( -path "./jobs/job-template.yaml" -o -path "./cron-job-configuration/*.yaml" \) \
              -exec sed -i "s|image:[[:space:]]*.*|image: $img|g" {} \;
            echo "Updated export-data manifests."
          else
            manifest="deployments/${svc_name}-deployment.yaml"
            if [ ! -f "$manifest" ]; then
              echo "ERROR: Manifest not found: $manifest"
              exit 1
            fi
            echo "=== Updating $manifest ==="
            sed -i "s|image:[[:space:]]*.*|image: $img|g" "$manifest"
            echo "Updated $svc_name manifest."
          fi
        done

        echo "All manifests updated."

  # ----------------------------------------------------------------------
  # Step 7: Commit & Push Manifest Changes
  # ----------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/git'
    id: 'commit-manifests'
    waitFor: ['update-manifests']
    entrypoint: 'bash'
    args:
      - -c
      - |
        if grep -q "SKIP_BUILD=true" /workspace/build_status.txt; then
          echo "Skipping commit."
          exit 0
        fi

        cd /workspace/unicommerce
        git config user.email "h4-cicd@h4-infra.iam.gserviceaccount.com"
        git config user.name "Cloud Build CI/CD"

        git add infra/kubernetes
        if git diff --cached --quiet; then
          echo "No manifest changes to commit."
          exit 0
        fi

        git commit -m "cloudbuild: update image tags to $SHORT_SHA [skip ci]"
        git push origin HEAD:$BRANCH_NAME
        echo "Manifest changes committed and pushed."

    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # ----------------------------------------------------------------------
  # Step 9: Deploy to GKE
  # ----------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-gke'
    waitFor: ['commit-manifests']
    entrypoint: 'bash'
    args:
      - -c
      - |
        if grep -q "SKIP_BUILD=true" /workspace/build_status.txt; then
          echo "Skipping GKE deployment."
          exit 0
        fi

        cd /workspace/unicommerce/infra/kubernetes
        gcloud container clusters get-credentials ${_GKE_CLUSTER} \
          --region ${_GKE_LOCATION} --project ${_PROJECT_ID} --dns-endpoint

        changed_services=$(cat /workspace/changed_services.txt)

        for svc in $changed_services; do
          svc_basename=$(basename "$svc")
          svc_name=$(echo "$svc_basename" | tr '[:upper:]' '[:lower:]' | sed 's|_|-|g')

          if [ "$svc_name" = "export-data" ]; then
            echo "=== Deploying export-data CronJobs ==="
            kubectl apply -f cron-job-configuration/ -n ${_NS}
            echo "Applied export-data CronJobs."
          else
            dep_name="${svc_name}-deployment"
            manifest="deployments/${svc_name}-deployment.yaml"
            echo "=== Deploying $dep_name ==="
            kubectl apply -f "$manifest" -n ${_NS}
            kubectl rollout status deployment/"$dep_name" -n ${_NS} --timeout=5m || \
              echo "Rollout warning: $dep_name may still be progressing."
          fi
        done

        echo "=== Deployment Summary ==="
        kubectl get deployments -n ${_NS}
        kubectl get cronjobs -n ${_NS}
        kubectl get pods -n ${_NS} --sort-by=.metadata.creationTimestamp

# ----------------------------------------------------------------------
# Secrets & Config
# ----------------------------------------------------------------------
availableSecrets:
  secretManager:
    - versionName: projects/h4-infra/secrets/praneeth_git/versions/latest
      env: 'SSH_KEY'

serviceAccount: 'h4-cicd@h4-infra.iam.gserviceaccount.com'

substitutions:
  _REGION: "asia-south1"
  _PROJECT_ID: "unicommerce-477809"
  _ARTIFACT_REPO: "unicommerce-prod"
  _GKE_CLUSTER: "unicom-cluster"
  _GKE_LOCATION: "asia-south1-a"
  _NS: "prod"

logsBucket: "gs://h4-cloudbuild-logs"

options:
  substitutionOption: "ALLOW_LOOSE"
  dynamicSubstitutions: true
  logging: GCS_ONLY

timeout: 7200s