services_dir: ./services
project_id: my-gcp-project
gar_name: my-artifact-registry
region: us-central1
global_tag: v1.0.0
max_processes: 4
use_gar: true
push_to_gar: true
services:
    - name: services/service-a
      image_name: service-a-image
      tag: v1.0.1
    - name: services/service-b
    - name: subdir/service-c
