apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch-gchat-adapter
  namespace: kubewatch
  labels:
    app: kubewatch-gchat-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch-gchat-adapter
  template:
    metadata:
      labels:
        app: kubewatch-gchat-adapter
    spec:
      serviceAccountName: kubewatch
      containers:
      - name: adapter
        image: asia-south1-docker.pkg.dev/muxly-h4/hypr4/kubewatch-adapter:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GCHAT_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: gchat-webhook-secret
              key: url
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kubewatch-gchat-adapter-service
  namespace: kubewatch
  labels:
    app: kubewatch-gchat-adapter
spec:
  selector:
    app: kubewatch-gchat-adapter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
