# This is a reusable workflow for scanning the repository's filesystem for vulnerabilities.
# It is called by other workflows and does not trigger on its own.

name: Security-scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner (Filesystem)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        exit-code: '0' # Don't fail the build, just report
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'