# This is a reusable workflow for running unit tests.
# It is called by other workflows and does not trigger on its own.

name: Tests

on:
  workflow_call:
    inputs:
      changed_dirs:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python test dependencies
        run: pip install pytest httpx

      - name: Run tests for changed services
        run: |
          echo "Running tests in the following directories: ${{ inputs.changed_dirs }}"
          for dir in ${{ inputs.changed_dirs }}; do
            # --- Go Test Runner ---
            if [ -f "$dir/go.mod" ]; then
              echo "--- Running tests in $dir ---"
              (cd "$dir" && go test ./...)
              echo "--- Running Go tests for service in '$dir' ---"
              (cd "$dir" && go mod tidy && go test ./...)
            # --- Python Test Runner ---
            elif [ -f "$dir/requirements.txt" ]; then
              echo "--- Running Python tests for service in '$dir' from 'tests/$dir' ---"
              pip install -r "$dir/requirements.txt"
              pytest "tests/$dir"
            fi
          done