name: Release Dockerz

on:
  push:
    branches: [ master ]
    paths:
      - 'dockerz/**'
      - '.goreleaser.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'dockerz/**'
      - '.goreleaser.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: |
        cd dockerz
        go test ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
        workdir: dockerz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deb:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build .deb packages
      run: |
        cd dockerz
        # Update changelog with current version
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "2.0.0")
        sed -i "s/dockerz (.*)/dockerz ($VERSION)/" debian/changelog

        # Build .deb package
        dpkg-buildpackage -us -uc

        # Move .deb files to workspace root
        mv ../dockerz_*.deb ../../

    - name: Upload .deb artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dockerz-deb-packages
        path: dockerz_*.deb

  update-install-branch:
    needs: [release, build-deb]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: install
        path: install-branch

    - name: Download .deb artifacts
      uses: actions/download-artifact@v3
      with:
        name: dockerz-deb-packages
        path: install-branch/apt/dockerz/

    - name: Update apt repository metadata
      run: |
        cd install-branch/apt

        # Generate Packages.gz
        dpkg-scanpackages dockerz /dev/null | gzip -9c > Packages.gz

        # Generate Release file
        cat > Release << 'EOF'
        Origin: DevOps Toolkit
        Label: DevOps Toolkit Repository
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: amd64 arm64
        Components: main
        Description: DevOps Toolkit Repository
        Date: $(date -R)
        EOF

        # Sign Release file (if GPG key available)
        if [ -n "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
          gpg --detach-sign --armor --output Release.gpg Release
          gpg --clearsign --output InRelease Release
        fi

    - name: Commit and push changes
      run: |
        cd install-branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update dockerz packages and repository metadata" || echo "No changes to commit"
        git push origin install