name: Setup GPG Key for Apt Repository

on:
  workflow_dispatch:
    inputs:
      gpg_key_id:
        description: 'GPG Key ID to use for signing'
        required: true
        type: string

jobs:
  setup-gpg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate GPG Key
      run: |
        # Install required packages
        sudo apt-get update
        sudo apt-get install -y gnupg rng-tools

        # Generate GPG key
        cat > gpg-key.conf << EOF
        %echo Generating a basic OpenPGP key
        Key-Type: RSA
        Key-Length: 4096
        Subkey-Type: RSA
        Subkey-Length: 4096
        Name-Real: DevOps Toolkit Repository
        Name-Comment: Apt Repository Signing Key
        Name-Email: devops-toolkit@github.com
        Expire-Date: 0
        %no-ask-passphrase
        %no-protection
        %commit
        %echo done
        EOF

        gpg --batch --generate-key gpg-key.conf

        # Export the key
        GPG_KEY_ID=$(gpg --list-keys --with-colons | grep '^pub' | head -n1 | cut -d: -f5)
        echo "GPG_KEY_ID=$GPG_KEY_ID" >> $GITHUB_ENV

        # Export private key for GitHub Secrets
        gpg --export-secret-keys --armor $GPG_KEY_ID > gpg-private-key.asc
        echo "GPG_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
        cat gpg-private-key.asc >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # Export public key
        gpg --export --armor $GPG_KEY_ID > gpg-public-key.asc

    - name: Display GPG Key Information
      run: |
        echo "Generated GPG Key ID: $GPG_KEY_ID"
        echo "Add the following as a GitHub Secret named 'GPG_PRIVATE_KEY':"
        echo ""
        cat gpg-private-key.asc
        echo ""
        echo "Public key for users to add to their apt keyring:"
        echo ""
        cat gpg-public-key.asc

    - name: Upload GPG keys as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gpg-keys
        path: |
          gpg-private-key.asc
          gpg-public-key.asc