name: Update Apt Repository

on:
  workflow_dispatch:
  push:
    branches: [ install ]
    paths:
      - 'apt/**'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: install

    - name: Update repository metadata
      run: |
        cd apt

        # Generate Packages.gz for all packages
        dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

        # Generate Release file
        cat > Release << 'EOF'
        Origin: DevOps Toolkit
        Label: DevOps Toolkit Repository
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: amd64 arm64
        Components: main
        Description: DevOps Toolkit Repository
        Date: $(date -R)
        EOF

        # Sign Release file (if GPG key available)
        if [ -n "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
          gpg --detach-sign --armor --output Release.gpg Release
          gpg --clearsign --output InRelease Release
        fi

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/install'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apt
        destination_dir: apt
        cname: scripts.addy-47.github.io

    - name: Commit metadata changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update apt repository metadata" || echo "No changes to commit"
        git push origin install